-- RXZ Gamer: tienda profesional, soporte, reseñas, métricas y arrepentimiento.

create table if not exists public.return_requests (
  id uuid primary key default gen_random_uuid(),
  request_code text not null unique,
  full_name text not null,
  email text not null,
  order_number text not null,
  detail text not null,
  status text not null default 'received' check (status in ('received','reviewing','resolved','rejected')),
  created_at timestamptz not null default now()
);

alter table public.return_requests enable row level security;
grant insert on public.return_requests to anon, authenticated;
grant select, update on public.return_requests to authenticated;

drop policy if exists "anyone can submit return request" on public.return_requests;
create policy "anyone can submit return request" on public.return_requests
for insert to anon, authenticated
with check (
  char_length(trim(full_name)) between 2 and 120 and
  char_length(trim(email)) between 5 and 200 and
  char_length(trim(order_number)) between 2 and 100 and
  char_length(trim(detail)) between 5 and 3000 and
  status = 'received'
);

drop policy if exists "admins manage return requests" on public.return_requests;
create policy "admins manage return requests" on public.return_requests
for all to authenticated
using (public.is_support_staff())
with check (public.is_support_staff());

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  brand text not null,
  name text not null,
  category text not null,
  subtitle text not null default '',
  description text not null default '',
  price numeric(12,2) not null check (price >= 0),
  old_price numeric(12,2) check (old_price is null or old_price >= price),
  stock integer not null default 0 check (stock >= 0),
  badge text,
  images jsonb not null default '[]'::jsonb,
  features jsonb not null default '[]'::jsonb,
  specs jsonb not null default '[]'::jsonb,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Los productos originales usan IDs 1 a 6 en el catálogo de respaldo.
-- Los nuevos comienzan en 1000 para que ambos catálogos convivan sin colisiones.
alter sequence if exists public.products_id_seq restart with 1000;

alter table public.products enable row level security;
grant select on public.products to anon, authenticated;
grant insert, update, delete on public.products to authenticated;
grant usage, select on sequence public.products_id_seq to authenticated;

drop policy if exists "published products are public" on public.products;
create policy "published products are public" on public.products
for select to anon, authenticated using (active or public.is_support_staff());

drop policy if exists "staff manages products" on public.products;
create policy "staff manages products" on public.products
for all to authenticated using (public.is_support_staff()) with check (public.is_support_staff());

create table if not exists public.product_reviews (
  id uuid primary key default gen_random_uuid(),
  product_id text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  order_id uuid not null references public.orders(id) on delete cascade,
  rating smallint not null check (rating between 1 and 5),
  comment text not null check (char_length(trim(comment)) between 5 and 1500),
  approved boolean not null default false,
  created_at timestamptz not null default now(),
  unique(product_id, user_id, order_id)
);

alter table public.product_reviews enable row level security;
grant select on public.product_reviews to anon, authenticated;
grant insert, update on public.product_reviews to authenticated;

drop policy if exists "approved reviews are public" on public.product_reviews;
create policy "approved reviews are public" on public.product_reviews
for select to anon, authenticated using (approved or user_id = auth.uid() or public.is_support_staff());

drop policy if exists "delivered customers review purchases" on public.product_reviews;
create policy "delivered customers review purchases" on public.product_reviews
for insert to authenticated with check (
  user_id = auth.uid() and exists (
    select 1 from public.orders o join public.order_items oi on oi.order_id = o.id
    where o.id = product_reviews.order_id and o.user_id = auth.uid() and o.status = 'delivered'
      and oi.product_id = product_reviews.product_id
  )
);

drop policy if exists "staff manages reviews" on public.product_reviews;
create policy "staff manages reviews" on public.product_reviews
for all to authenticated using (public.is_support_staff()) with check (public.is_support_staff());

create table if not exists public.store_events (
  id bigint generated always as identity primary key,
  event_name text not null,
  product_id text,
  user_id uuid references auth.users(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.store_events enable row level security;
grant insert on public.store_events to anon, authenticated;
grant select on public.store_events to authenticated;
grant usage, select on sequence public.store_events_id_seq to anon, authenticated;

drop policy if exists "store events can be recorded" on public.store_events;
create policy "store events can be recorded" on public.store_events
for insert to anon, authenticated with check (
  event_name in ('product_view','add_to_cart','begin_checkout','purchase','support_open')
  and (user_id is null or user_id = auth.uid())
);

drop policy if exists "staff reads store events" on public.store_events;
create policy "staff reads store events" on public.store_events
for select to authenticated using (public.is_support_staff());

alter table public.support_conversations add column if not exists last_staff_read_at timestamptz;
alter table public.support_conversations add column if not exists order_number text;
